#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
# declare -A color

gaps["top"]="8"
gaps["bottom"]="8"
gaps["left"]="8"
gaps["right"]="8"
gaps["inner"]="8"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         on

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config split_ratio                 0.50
yabai -m config split_type                  auto
yabai -m config auto_balance                on

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m space 1 --label main
yabai -m space 2 --label dev1
yabai -m space 3 --label dev2
yabai -m space 4 --label edit
yabai -m space 5 --label view
yabai -m space 6 --label play

yabai -m config external_bar                all:28:0

yabai -m window --toggle float
yabai -m window --toggle sticky
yabai -m window --toggle level above

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add app="^Floorp$" title="^Library" manage=off
yabai -m signal --add event=window_created app="^Floorp$" title="^Library" action="yabai -m window --resize abs:800:600; yabai -m window --move abs:1600:200"
# yabai doesn't seem able to see System Settings so this line dose nothing
# yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off


set +x
printf "yabai: configuration loaded...\\n"

borders active_color=0xff5e81ac inactive_color=0x665e81ac width=4.0 &
