#+OPTIONS: toc:nil

# dotfiles

A collection of my personal dotfiles.

All the folders here, with the exemption of /scripts/, should be either symlinked or copied into '/\slash{}home\slash{}<username>\slash{}.config/'.

Files in the scripts directory should be symlinked or copied into '/\slash{}home\slash{}<username>\slash{}.scripts/'. 

I use these files more as templates due to running them on several machines with some specific settings I need or like for each.
This version of the dotfiles are compatible with my Manjaro Linux installation, whereas a version compatible with my OpenSUSE Tumbelweed installation can be found the opensuse branch. An experimental WSL2 setup used in Debian under WSL2 is also available in the WSL branch.

There is a chance that some things I haven't actually used in a while might be broken. Please don't hesitate to contact me if you encounter any such issues.

Note: many of the config files, scripts, functions etc. throughout these dotfiles were taken from various sources around the web.  I have randomly picked up stuff I found useful from all over, and I never kept a record of what came from where.
Chances are, if it's anything pretty good than it wasn't me and credit is due elsewhere!


