#+OPTIONS: toc:nil
#+TITLE: A collection of my personal dotfiles.

I use these files more as templates due to running them on several machines with
some specific settings I need or like for each. This version of the dotfiles are
compatible with my Manjaro Linux installation, whereas a version compatible with
my OpenSUSE Tumbelweed installation can be found the opensuse branch. An
experimental WSL2 setup used in Debian under WSL2 is also available in the WSL
branch.

There is a chance that some things I haven't actually used in a while might be
broken. Please don't hesitate to contact me if you encounter any such issues.

I'm currently using Xmonad as my main window manager, and hence some things in
the i3 settings might not be updated. For instance, some changes in the scripts
might not be compatible with how i3 calls them. These should all be easy to fix,
but might not currently work as intended out of the box.

* How I use these files
All the folders here, with the exception of /scripts/ and /.doom/, should be
either symlinked or copied into /\slash{}home\slash{}<username>\slash{}.config/
or /~\slash{}.config/ in short.

Files in the scripts directory should be symlinked or copied into
/~\slash{}.scripts/.

The xmonad folder will not work properly if placed in /~\slash{}.config/
folder without some additional work. Detail about this problem can be found
here: https://github.com/xmonad/xmonad/issues/164. In short, you have to create a
folder /~\slash{}.local\slash{}share\slash{}xmonad/ so that
/~\slash{}.xmonad/ doesn't get created the next time xmonad is recompiled.
Alternatively, the xmonad folder can just be symlinked or moved to
/~\slash{}.xmonad/.

* Note
Many of the config files, scripts, functions etc. throughout these dotfiles were
taken from various sources around the web. I have randomly picked up stuff I
found useful from all over, and I never kept a good record of what came from
where. Chances are, if it's anything that's particularly impressive then it
wasn't writen by me and credit is due elsewhere! However there is no line of
code that I havn't gone over and made sure to understand so if you encounter
anything problematic please get in touch!
