#+OPTIONS: toc:nil
#+TITLE: A collection of my personal dotfiles.

This is my collection of dotfiles for most of the programs I use on a daily
basis between my various machines. The current version of the dotfiles should be
mostly distro agnostic and compatible at least with both my OpenSUSE Tumbelweed
and Manjaro Linux installations. Some things, like the CPU temperature sensor is
still system specific and will likely not work on your system out of the box.

There is a good chance that some things haven't been used in a while and might be
broken. If so, I would love to know about it so please either file an issue here
or contact me directly if you find any such things.

An experimental WSL2 branch is also available, but has not been updated in a
while and there is no grantee it will work at all! It has not been updated to be
distro agnostic and some features will only work in Debian.

* How to use these files
All the folders here, with the exception of /scripts/ and /.doom/, should be
either symlinked or copied into /\slash{}home\slash{}<username>\slash{}.config/
or /~\slash{}.config/ in short.

The xmonad folder will not work properly if placed in /~\slash{}.config/
folder without some additional work. Detail about this problem can be found
here: https://github.com/xmonad/xmonad/issues/164. In short, you have to create a
folder /~\slash{}.local\slash{}share\slash{}xmonad/ so that
/~\slash{}.xmonad/ doesn't get created the next time xmonad is recompiled.
Alternatively, the xmonad folder can just be symlinked or moved to
/~\slash{}.xmonad/.

Files in the scripts directory should be symlinked or copied into
/~\slash{}.scripts/.  There is one exception which is
/\slash{}scripts/gethwmon.sh that is used to export an environment variable
with the location of the temperature sensor which should be placed in
/\slash{}etc\slash{}profile.d/ in so it can be executed once at startup. This
script is only used for showing the CPU temperature in xmobar - some other
options of how to get that reading without having to use the
/\slash{}scripts/gethwmon.sh script are explained in /\slash{}scripts/ctemp.

* Note
Many of the config files, scripts, functions etc. throughout these dotfiles were
taken from various sources around the web. I have randomly picked up stuff I
found useful from all over, and I never kept a good record of what came from
where. Chances are, if it's anything that's particularly impressive then it
wasn't writen by me and credit is due elsewhere! However there is no line of
code that I haven't gone over and made sure to understand so if you encounter
anything problematic please get in touch!

** Where is i3?
I've been using Xmonad as my main window manager for the past few years, and
hence some things in the i3 settings might not be updated and/or are broken. For
this reason I have removed i3 and polybar from the =master= branch, but you can
find them in older branches if you so wish.
