#!/usr/bin/env bash

# Prints an integer value of the temperature value directly from the sysfs path
# Use `sensors` to find preferred temperature source, then run
# $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
# to find path to desired file

# value=$(</sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon3/temp2_input)

value=$(<$hwmon_id)
value=$((value/1000))
printf "$value\n"
